version: "3"
services:
  mha-manager:
    container_name: mha-manager
    env_file:
      - ./.dynamic_env
    stdin_open: true
    tty: true
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      MHA_SHARE_SSHKEYS_PATH: /root/mha-ssh/sshkeys
      CONTAINER_NAME: mha-manager
      MYSQL_USER: ${MYSQL_REMOTE_USER_MASTER}
      MYSQL_PASSWORD: ${MYSQL_REMOTE_USER_PASSWORD_MASTER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - '23506:3306'
    volumes:
      - "../shares/.ssh/mha-manager:/root/.ssh"
      - "./mha-manager/mha-ssh:/root/mha-ssh/"
      - "./mha-manager/conf:/etc/mha"
      - "./mha-manager/work:/usr/local/mha/work"
      - "./mha-manager/log:/usr/local/mha/log"
    # Where our data will be persisted
    networks:
      master_net-mysql:
        ipv4_address: ${DOCKER_MHA_IP}

networks:
  master_net-mysql:
    external:
      name: master_net-mysql