version: "3"
services:
  db-master:
    container_name: ${MASTER_CONTAINER_NAME}
    privileged: true
    build:
      context: ./
      dockerfile: master/Dockerfile
    environment:
      MHA_SHARE_SSHKEYS_PATH: /root/mha-ssh/sshkeys
      CONTAINER_NAME: ${MASTER_CONTAINER_NAME}
      MYSQL_USER: ${MYSQL_REMOTE_USER_MASTER}
      MYSQL_PASSWORD: ${MYSQL_REMOTE_USER_PASSWORD_MASTER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - '${MACHINE_MASTER_DB_PORT}:3306'
      - '${MACHINE_MASTER_SSH_PORT}:22'
    # Where our data will be persisted
    volumes:
      - "./mha-manager/mha-ssh/:/root/mha-ssh/"
      - ${MYSQL_DATA_PATH_MASTER}:/var/lib/mysql
      - ${MYSQL_FILE_PATH_MASTER}:/var/lib/mysql-files
      - ${MYSQL_LOG_PATH_MASTER}:/var/log/mysql
      - ${MYSQL_ETC_PATH_MASTER}:/var/tmp
      - ./master/my.cnf:/etc/mysql/my.cnf
    networks:
       net-mysql:
          ipv4_address: ${MACHINE_MASTER_IP}

# Names our volume
volumes:
  my-db-master:
  my-db-slave: 

networks:
  net-mysql:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16
          gateway: 10.3.0.1